#!/bin/bash

# Exécute la commande pwd pour obtenir le répertoire courant
current_dir=$(pwd)

# Le fichier où la modification doit être effectuée
file="includes/pipex.h"

# Indicateur pour vérifier si la ligne #define PWD a été trouvée
found=0

# Remplacer la ligne #define PWD si elle existe
if grep -q "^# define PWD" "$file"; then
    sed -i "s|^# define PWD.*|# define PWD \"$current_dir\"|" "$file"
    found=1
fi

# Si la ligne #define PWD n'a pas été trouvée, l'ajouter après le dernier #define
if [[ $found -eq 0 ]]; then
    # Trouver la dernière ligne commençant par #define
    last_define=$(grep -n "^# define" "$file" | tail -n 1 | cut -d ":" -f 1)
    # Insérer la nouvelle ligne après la dernière ligne #define
    sed -i "${last_define}a\\
# define PWD \"$current_dir\"
" "$file"
fi
